import type { Character } from '@/entities/character/types'

export function makeChar(overrides: Partial<Character> = {}): Character {
  return {
    id: 'test-id',
    schemaVersion: 3,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
    name: 'Test Character',
    race: 'Human',
    classId: 'Fighter',
    background: 'Soldier',
    level: 1,
    experiencePoints: 0,
    abilityScores: { str: 10, dex: 10, con: 10, int: 10, wis: 10, cha: 10 },
    hitPoints: { current: 10, max: 10, temp: 0 },
    armorClass: 10,
    speed: 30,
    initiative: 0,
    proficiencyBonus: 2,
    bonusHpPerLevel: 0,
    equipment: {
      armorId: null, hasShield: false, shieldId: null,
      helmetId: null, necklaceId: null, capeId: null, legsId: null,
      bootsId: null, glovesId: null,
      ring1Id: null, ring2Id: null, amuletId: null,
    },
    savingThrowProficiencies: [],
    skillProficiencies: {},
    spellIds: [],
    preparedSpellIds: [],
    spellSlots: {},
    concentrationSpellId: null,
    weapons: [],
    conditionIds: [],
    resources: {},
    deathSaves: { successes: 0, failures: 0 },
    inspiration: 0,
    hitDiceUsed: 0,
    gold: 0,
    ownedItemIds: [],
    feats: [],
    completedAsiLevels: [],
    activeSummons: [],
    notes: '',
    ...overrides,
  }
}
